export default {
  DIARY_INDEX_PENDING: "DIARY_INDEX_PENDING",
  DIARY_INDEX_REJECTED: "DIARY_INDEX_REJECTED",
  DIARY_INDEX_FULFILLED: "DIARY_INDEX_FULFILLED",

  DIARY_CREATE_PENDING: "DIARY_CREATE_PENDING",
  DIARY_CREATE_REJECTED: "DIARY_CREATE_REJECTED",
  DIARY_CREATE_FULFILLED: "DIARY_CREATE_FULFILLED",

  DIARY_DESTROY_PENDING: "DIARY_DESTROY_PENDING",
  DIARY_DESTROY_REJECTED: "DIARY_DESTROY_REJECTED",
  DIARY_DESTROY_FULFILLED: "DIARY_DESTROY_FULFILLED"
};
