export default {
  FRIEND_REQUEST_INDEX_PENDING: "FRIEND_REQUEST_INDEX_PENDING",
  FRIEND_REQUEST_INDEX_REJECTED: "FRIEND_REQUEST_INDEX_REJECTED",
  FRIEND_REQUEST_INDEX_FULFILLED: "FRIEND_REQUEST_INDEX_FULFILLED",

  FRIEND_REQUEST_CREATE_PENDING: "FRIEND_REQUEST_CREATE_PENDING",
  FRIEND_REQUEST_CREATE_REJECTED: "FRIEND_REQUEST_CREATE_REJECTED",
  FRIEND_REQUEST_CREATE_FULFILLED: "FRIEND_REQUEST_CREATE_FULFILLED",

  FRIEND_REQUEST_CONFIRM_PENDING: "FRIEND_REQUEST_CONFIRM_PENDING",
  FRIEND_REQUEST_CONFIRM_REJECTED: "FRIEND_REQUEST_CONFIRM_REJECTED",
  FRIEND_REQUEST_CONFIRM_FULFILLED: "FRIEND_REQUEST_CONFIRM_FULFILLED",

  FRIEND_REQUEST_DECLINE_PENDING: "FRIEND_REQUEST_DECLINE_PENDING",
  FRIEND_REQUEST_DECLINE_REJECTED: "FRIEND_REQUEST_DECLINE_REJECTED",
  FRIEND_REQUEST_DECLINE_FULFILLED: "FRIEND_REQUEST_DECLINE_FULFILLED"
};
