export default {
  FRIEND_REQUEST_INDEX_PENDING: "FRIEND_REQUEST_INDEX_PENDING",
  FRIEND_REQUEST_INDEX_REJECTED: "FRIEND_REQUEST_INDEX_REJECTED",
  FRIEND_REQUEST_INDEX_FULFILLED: "FRIEND_REQUEST_INDEX_FULFILLED",

  FRIEND_REQUEST_CREATE_PENDING: "FRIEND_REQUEST_CREATE_PENDING",
  FRIEND_REQUEST_CREATE_REJECTED: "FRIEND_REQUEST_CREATE_REJECTED",
  FRIEND_REQUEST_CREATE_FULFILLED: "FRIEND_REQUEST_CREATE_FULFILLED",

  FRIEND_REQUEST_UPDATE_PENDING: "FRIEND_REQUEST_UPDATE_PENDING",
  FRIEND_REQUEST_UPDATE_REJECTED: "FRIEND_REQUEST_UPDATE_REJECTED",
  FRIEND_REQUEST_UPDATE_FULFILLED: "FRIEND_REQUEST_UPDATE_FULFILLED",

  FRIEND_REQUEST_DESTROY_PENDING: "FRIEND_REQUEST_DESTROY_PENDING",
  FRIEND_REQUEST_DESTROY_REJECTED: "FRIEND_REQUEST_DESTROY_REJECTED",
  FRIEND_REQUEST_DESTROY_FULFILLED: "FRIEND_REQUEST_DESTROY_FULFILLED"
};
