export default {
  FRIEND_INDEX_PENDING: "FRIEND_INDEX_PENDING",
  FRIEND_INDEX_REJECTED: "FRIEND_INDEX_REJECTED",
  FRIEND_INDEX_FULFILLED: "FRIEND_INDEX_FULFILLED",

  FRIEND_CREATE_PENDING: "FRIEND_CREATE_PENDING",
  FRIEND_CREATE_REJECTED: "FRIEND_CREATE_REJECTED",
  FRIEND_CREATE_FULFILLED: "FRIEND_CREATE_FULFILLED",

  FRIEND_UPDATE_PENDING: "FRIEND_UPDATE_PENDING",
  FRIEND_UPDATE_REJECTED: "FRIEND_UPDATE_REJECTED",
  FRIEND_UPDATE_FULFILLED: "FRIEND_UPDATE_FULFILLED",

  FRIEND_DESTROY_PENDING: "FRIEND_DESTROY_PENDING",
  FRIEND_DESTROY_REJECTED: "FRIEND_DESTROY_REJECTED",
  FRIEND_DESTROY_FULFILLED: "FRIEND_DESTROY_FULFILLED"
};
